server:
  port: 8080
datasource:
  url: tcp(host:port)
  username:
  password:
  database: pmkit
  driver-name: mysql
  max-open-connections:
  max-idle-connections:
app:
  default-uid: 1690713268944900096
